/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const AllProgresLazyRouteImport = createFileRoute('/allProgres')()

const AllProgresLazyRoute = AllProgresLazyRouteImport.update({
  id: '/allProgres',
  path: '/allProgres',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/allProgres.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allProgres': typeof AllProgresLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allProgres': typeof AllProgresLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allProgres': typeof AllProgresLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/allProgres'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/allProgres'
  id: '__root__' | '/' | '/allProgres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllProgresLazyRoute: typeof AllProgresLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/allProgres': {
      id: '/allProgres'
      path: '/allProgres'
      fullPath: '/allProgres'
      preLoaderRoute: typeof AllProgresLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllProgresLazyRoute: AllProgresLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
